### ISSUE TITLE
你好，按照文档里面的说明生成的Charles.jar, 替换原charles安装目录下的Charles.jar，重启Charles后菜单中没有新加的选项

### ISSUE THREAD

**Issue by 15026841910** [leafyin/charles-diy-plugin#1]
你好，按照文档里面的说明生成的Charles.jar, 替换原charles安装目录下的Charles.jar，重启Charles后菜单中没有新加的选项，以下是我的操作步骤：
1. clone 你的repo （代码未做改动）
2. 本地按照project的readme操作，生成了新的Charles.jar
3. 替换Charles安装目录下的Charles.jar文件，重启Charles
4. 鼠标右键response，查看菜单选项 （预期应该有自定义的菜单名称，而实际上没有，效果如下图）
<img width="312" alt="image" src="https://github.com/user-attachments/assets/371d1ced-2ecf-41df-a548-66ccde0b6f98">

本地环境：

- Mac OS
- Charles: 4.6.2
- JDK: 11

<img width="456" alt="image" src="https://github.com/user-attachments/assets/81a6660b-d7bd-448a-9e1e-f9a3e8279378">

**Comment by leafyin** [comment]
执行了updateCharles.sh脚本吗？需要将编译后的.class文件重新替换到原来的jar包内容

**Comment by 15026841910** [comment]
执行了并且替换了原来的jar包，以下是执行的脚本内容：
#!/bin/bash
#将你需要的添加进jar包的文件写到下面
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/CharlesUrlDecode.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/CharlesUrlDecodeText.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/TransactionViewerPopupMenu.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/CharlesUrlDecodeTextComponent.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/HttpUtils.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/JsonUtils.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar /Users/xxxx/code/11129/charles-diy-plugin/out/production/charles-diy-plugin/com/xk72/charles/gui/transaction/popups/ResultDialog.class

**Comment by leafyin** [comment]
好的，我大概知道什么问题了，稍等发布一个提交

**Comment by leafyin** [comment]
问题出在你更新的时候，也就是执行脚本的时候，应该按照原来updateCharles.sh来。只需要你需要做修改charles.jar的路径即可

**Comment by leafyin** [comment]
你的脚本我给你更新一下，在你的设备上把idea的build后out目录内的com后的目录直接拷贝出来放到根目录下，然后直接这个脚本，因为你在com目录前面添加的路径相当于给jar包生成了一个新的目录，所以没有改掉源代码，我现在把git上的jar包改到4.6.5了你还是用4.6.2就行
`jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/CharlesUrlDecode.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/CharlesUrlDecodeText.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/TransactionViewerPopupMenu.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/CharlesUrlDecodeTextComponent.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/HttpUtils.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/JsonUtils.class
jar -uf /Users/xxxx/code/11129/charles-diy-plugin/charles.jar com/xk72/charles/gui/transaction/popups/ResultDialog.class`

**Comment by leafyin** [comment]
在redeme中有一步你可能没执行，前面三个目录是不需要的
![ae2db41d-320d-49b8-a9dc-e9e498d51aee](https://github.com/user-attachments/assets/b0c94d9b-3d6f-4cff-a34c-569cfa1a0be6)

**Comment by leafyin** [comment]
readme我会再优化详细一点

**Comment by 15026841910** [comment]
感谢回复，按照您的建议试了下，编出来的jar包替换我本机Charles安装目录下的jar包后，重启Charles页面显示异常
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/8059ce6a-47e7-450b-8307-718c5c622fe8">
是否因为您用的是windows的charles.jar，我的本地环境是Mac OS ?

**Comment by 15026841910** [comment]
Charles报错日志：
2024/12/02 22:22:43	Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedClassVersionError: com/xk72/charles/gui/transaction/popups/TransactionViewerPopupMenu has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
2024/12/02 22:22:43		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
2024/12/02 22:22:43		at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
2024/12/02 22:22:43		at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
2024/12/02 22:22:43		at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
2024/12/02 22:22:43		at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
2024/12/02 22:22:43		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
2024/12/02 22:22:43		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
2024/12/02 22:22:43		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
2024/12/02 22:22:43		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.transaction.s.j(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.transaction.e.d(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.transaction.e.j(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.transaction.e.<init>(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.transaction.frames.o.<init>(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.transaction.frames.n.<init>(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.session.SessionFrame.init(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.session.AbstractSessionFrame.<init>(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.session.SessionFrame.<init>(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.k.a(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.h.a(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.h.j(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.CharlesFrame$17.actionPerformed(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.CharlesFrame.b(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.CharlesFrame.init(Unknown Source)
2024/12/02 22:22:43		at com.xk72.charles.gui.V.run(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
2024/12/02 22:22:43		at java.base/java.security.AccessController.doPrivileged(Native Method)
2024/12/02 22:22:43		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
2024/12/02 22:22:43		at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by leafyin** [comment]
不是，跟系统环境没关系，这个报错是Charlse 4.6.5的jdk编译版本太低导致的，你build出来的class文件编译版本过高，这个时候你要build的话需要用老一些的版本编译，比如1.7&1.8，不要使用openjdk

**Comment by leafyin** [comment]
有这个报错说明build后的class文件写入成功了，现在是运行不了版本太高的编译的class所产生的异常，切换更老版本的jdk重新编译即可

**Comment by leafyin** [comment]
有两个文件我做了更改，改成了支持java11的特性，本地环境jdk和语言级别要相同，过高的jdk会导致编译错误和运行出错，你可以pull我最新的更改然后再次执行shell尝试

**Comment by 15026841910** [comment]
现在正常了，非常感谢大佬的支持！
